### ISSUE TITLE
Can't load the module

### ISSUE THREAD

**Issue by MrCoala** [In-line/grip#115]
I just installed grip but it seems to crash the server upon module load. See console output:

Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
BFD: Warning: /home/tfc_servers/esclantest/core is truncated: expected core file size >= 125870080, found: 1048576.
Cannot access memory at address 0xf77ec908
Cannot access memory at address 0xf77ec904
Failed to read a valid object file image from memory.
Cannot access memory at address 0xf77ec908
Cannot access memory at address 0xf77ec904
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xffc31110
email debug.log to linux@valvesoftware.com
Sat Jul  6 22:17:52 CEST 2019: Server restart in 10 seconds

**Comment by In-line** [comment]
Hi. This is very interesting, my best guess is that some configuration file is missing. Anyway, it's better to do exactly what log says.

`Run with RUST_BACKTRACE=1 environment variable to display a backtrace.`

And send logs with backtrace, so I will be able to identify where is issue. Sometimes it's better to read logs and do what they tell. Non-developer can understand them too!

If you do it tomorrow, I will fix this immediately. And please mention what version of GRIP you use.

**Comment by In-line** [comment]
You should run like this `RUST_BACKTRACE=1 ./hlds_run -myoption1 -myoption2`

**Comment by MrCoala** [comment]
This is what i get with backtrace enabled:

Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
thread 'unnamed' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0: unknown
   1: unknown
   2: unknown
   3: unknown
   4: unknown
   5: unknown
   6: unknown
   7: unknown
   8: unknown
   9: _Z25api_caller_void_args_voidPKvS0_
  10: _Z23main_hook_function_voidj10enum_api_tjPKv
  11: _ZL13mm_StartFramev
  12: SV_Physics
             at ../engine/sv_phys.c:1985
  13: SV_ActivateServer
             at ../engine/sv_main.c:7226
  14: Host_Map.part.19
             at ../engine/host_cmd.c:1297
  15: Host_Map_f.part.27
             at ../engine/host_cmd.c:1280
             at ../engine/host_cmd.c:1451
  16: Cmd_ExecuteStringWithPrivilegeCheck.part.4
             at ../engine/cmd.c:1196
  17: Cbuf_ExecuteFromBuffer
             at ../engine/cmd.c:1155
             at ../engine/cmd.c:244
  18: Cbuf_Execute
             at ../engine/cmd.c:262
  19: Host_InitializeGameDLL
             at ../engine/host_cmd.c:221
  20: _Z12Sys_InitGamePcS_Pvi
             at ../engine/sys_dll2.cpp:806
  21: _ZN7CEngine4LoadEbPcS0_
             at ../engine/sys_engine.cpp:193
  22: _ZN19CDedicatedServerAPI4InitEPcS0_PFP14IBaseInterfacePKcPiES7_
             at ../engine/sys_dll2.cpp:1189
  23: _Z9RunServerv
             at ../dedicated/sys_ded.cpp:646
  24: main
             at ../dedicated/sys_ded.cpp:1146
  25: __libc_start_main
  26: <unknown>
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
BFD: Warning: /home/tfc_servers/esclantest/core is truncated: expected core file size >= 137990144, found: 1044480.
Cannot access memory at address 0xf7782908
Cannot access memory at address 0xf7782904
Failed to read a valid object file image from memory.
Cannot access memory at address 0xf7782908
Cannot access memory at address 0xf7782904
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xffa2af70

**Comment by In-line** [comment]
How did you installed module? I will compile today to get better
backtraces, but I think you installed it as a metamod module, not AMXX mod
one.

**Comment by MrCoala** [comment]
It is installed as amxmodx module.

I freshly installed the server to test GRIP. This is what i get when i use meta list (without trying to load  grip ofc):

meta list
Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.2    ini   Start ANY
 [ 2] MySQL            RUN   -    mysql_amxx_i386.  v1.8.2    pl1   ANY   ANY
 [ 3] Fun              RUN   -    fun_amxx_i386.so  v1.8.2    pl1   ANY   ANY
 [ 4] Engine           RUN   -    engine_amxx_i386  v1.8.2    pl1   ANY   ANY
 [ 5] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.2    pl1   ANY   ANY
 [ 6] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.2    pl1   ANY   ANY
6 plugins, 6 running

meta version
Metamod v1.21p37  2013/05/30 (5:13)
by Will Day
   http://www.metamod.org/
 Patch: Metamod-P (mm-p) v37
 by Jussi Kivilinna
    http://metamod-p.sourceforge.net/
compiled: May 30 2013, 11:41:16 EET (optimized)


version (tfc server version)
Protocol version 48
Exe version 1.1.2.2/Stdio (tfc)
Exe build: 15:52:40 Apr  3 2019 (8196)

when i check for dependencies on your library i get this:
grip_amxx_i386.so
        linux-gate.so.1 (0xf778d000)
        libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf71b7000)
        libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7162000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf6faa000)
        /lib/ld-linux.so.2 (0xf778f000)


Just googled it and it seems that linux-gate.so.1 is kernel related and doesnt need to be on the fs. I have no clue what is causing the crash. Is there any more information i could assist you with?

**Comment by In-line** [comment]
Nothing particular. Every dependency should be present in your system or
GRIP wouldn't load. Currently it loads and crashes later.

I advice you to wait little for version with not stripped symbols, so we
could get better backtrace.

Can you explain me how do you reproduce this issue? You should have just
dropped module so, necessary configs and compiled plugin. Nothing should be
written in metamod `plugins.ini`.

GRIP is used in several servers. I will release a version with better
backtrace as soon as I'm able and issue will be hopefully fixed.

**Comment by MrCoala** [comment]
I unpacked your provided archive into the tfc folder and everyone went where it belongs to (the module to the amxmodx modules folder f.e.) and the only plugin in plugins.ini is amxmodx. I will provide you with a better crashlog as soon as you provide the version with debug informations. Thank you for your help

**Comment by In-line** [comment]
@MrCoala Try this out, when it will compile and upload to GitHub. https://github.com/In-line/grip/releases/tag/0.1.4-beta

**Comment by In-line** [comment]
There is even an attempt to fix possible cause of issue. Waiting for good news!

**Comment by MrCoala** [comment]
I can't compile it.

See http://paste.skillzworld.eu/livakohagu.sql

I used your precompiled binary before.

**Comment by In-line** [comment]
No need to compile it, use precompiled binary from releases. Exact compile environment can be found in .travis.yml no need to struggle with C++.

**Comment by MrCoala** [comment]
i used this:

 RUST_BACKTRACE=1 ./hlds_run -game tfc +maxplayers 18 +port 29099 +map well -debug -insecure -gdb gdb


I am afraid there is less debug information than before.

Output:


Enabling debug mode
Auto-restarting the server on crash

Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 20
Forcing breakpad minidump interfaces to load
dlopen failed trying to load:
/root/.steam/sdk32/steamclient.so
with error:
/root/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Protocol version 48
Exe version 1.1.2.2/Stdio (tfc)
Exe build: 15:52:40 Apr  3 2019 (8196)
STEAM Auth Server
Server IP address 148.251.193.12:29099

   Metamod version 1.21p37 Copyright (c) 2001-2013 Will Day
     Patch: Metamod-P (mm-p) v37 Copyright (c) 2004-2013 Jussi Kivilinna
   Metamod comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.


   AMX Mod X version 1.8.2 Copyright (c) 2004-2006 AMX Mod X Development Team
   AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
   This is free software and you are welcome to redistribute it under
   certain conditions; type 'amxx gpl' for details.

stray key in process_key: item_getiteminfo 70
L 07/08/2019 - 23:33:56: -------- Mapchange to well --------
[AMXX] Loaded 2 admins from file
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
CAppInfoCacheReadFromDiskThread took 1 milliseconds to initialize
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
dlopen failed trying to load:
/root/.steam/sdk32/steamclient.so
with error:
/root/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Segmentation fault (core dumped)
BFD: Warning: /home/tfc_servers/esclantest/core is truncated: expected core file size >= 125870080, found: 1048576.
Cannot access memory at address 0xf773a908
Cannot access memory at address 0xf773a904
Failed to read a valid object file image from memory.
Cannot access memory at address 0xf773a908
Cannot access memory at address 0xf773a904
debug.cmds:4: Error in sourced command file:
Cannot access memory at address 0xffcc605c
email debug.log to linux@valvesoftware.com
Mon Jul  8 23:33:57 CEST 2019: Server restart in 10 seconds

**Comment by In-line** [comment]
Hi. Try one more time, my guess is that gdb interferes and backtrace isn't
printed. Actually on my PC it happens 1 time in 5 tries.

**Comment by In-line** [comment]
Closing, because of inactivity.
