### ISSUE TITLE
/lib/libc.so.6: version `GLIBC_2.18' not found (centos 7)

### ISSUE THREAD

**Issue by ady2324** [In-line/grip#141]
hi all
i can't start grip mode give this error
AMXX] Module "cstrike/addons/amxmodx/modules/grip_amxx_i386.so" failed to load (/lib/libc.so.6: version `GLIBC_2.18' not found (required by cstrike/addons/amxmodx/modules/grip_amxx_i386.so))
pls help need this plugin
[ AMXX] Plugin "proxy_check.amxx" failed to load: Module/Library "grip" required for plugin.  Check modules.ini.

**Comment by In-line** [comment]
Duplicate #127
